"""add pinout

Revision ID: 943550adda25
Revises: 3f2f3d104449
Create Date: 2021-09-18 13:33:05.577881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943550adda25'
down_revision = '3f2f3d104449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pin_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pin_number', sa.Integer(), nullable=True),
    sa.Column('pin_value', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pin_out')
    # ### end Alembic commands ###
